#!/usr/bin/env python3
from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
import pandas as pd

from src.reporting.latex import write_tex
from src.reporting.templates import DISCUSSION_TEMPLATE, METHODOLOGY_TEMPLATE
from src.utils.io import read_json
from src.utils.io import ensure_dir


def results_section() -> str:
    metrics_path = Path("results/metrics.csv")
    safety_path = Path("results/safety_metrics.csv")
    latency_path = Path("results/latency_metrics.csv")
    if not metrics_path.exists() or not safety_path.exists() or not latency_path.exists():
        return (
            "\\section{Results}\n"
            "TODO: metric generated by scripts/run_experiments.py. "
            "No quantitative results are reported because measured result files are absent.\n"
        )
    metrics = pd.read_csv(metrics_path)
    safety = pd.read_csv(safety_path)
    latency = pd.read_csv(latency_path)
    fallback_note = ""
    metadata_files = sorted(Path("results/traces").glob("*.metadata.json"))
    source_note = ""
    if metadata_files:
        metadata = read_json(metadata_files[0])
        if metadata.get("source") == "synthetic_fallback":
            fallback_note = (
                " The current run used the documented synthetic fallback because no audited real "
                "dataset files were available locally; these values are valid only for the generated "
                "simulation traces."
            )
        else:
            source_note = (
                f" The experiment trace metadata reports source \\texttt{{{metadata.get('source', 'unknown')}}}. "
                f"Limitations: {metadata.get('limitations', 'none recorded')}"
            )
    best = metrics.groupby("method", as_index=False)["mae"].mean().sort_values("mae").head(1)
    method = best.iloc[0]["method"]
    mae = best.iloc[0]["mae"]
    method_table = metrics.groupby("method", as_index=False)[["mae", "rmse", "p95_absolute_error"]].mean().sort_values("mae")
    method_lines = [
        f"\\texttt{{{row.method}}}: MAE={row.mae:.4f}, RMSE={row.rmse:.4f}, P95AE={row.p95_absolute_error:.4f}"
        for row in method_table.itertuples()
    ]
    safety_lines = []
    if "agent_variant" in safety.columns:
        safety_summary = safety.groupby("agent_variant", as_index=False)[
            ["unsafe_actions_proposed", "unsafe_actions_blocked_by_verifier", "unsafe_actions_executed", "safe_actions_accepted", "average_refinement_cycles"]
        ].mean()
        safety_lines = [
            (
                f"\\texttt{{{row.agent_variant}}}: unsafe proposed={row.unsafe_actions_proposed:.2f}, "
                f"blocked={row.unsafe_actions_blocked_by_verifier:.2f}, unsafe executed={row.unsafe_actions_executed:.2f}, "
                f"safe accepted={row.safe_actions_accepted:.2f}, refinement cycles={row.average_refinement_cycles:.2f}"
            )
            for row in safety_summary.itertuples()
        ]
    latency_summary = latency.groupby("method", as_index=False).mean(numeric_only=True).sort_values(
        ["fuzzy_consensus_latency_seconds", "deterministic_simulation_latency_seconds"]
    )
    latency_lines = [
        (
            f"\\texttt{{{row.method}}}: consensus latency={row.fuzzy_consensus_latency_seconds:.6f}s, "
            f"agent/simulation latency={row.deterministic_simulation_latency_seconds:.6f}s"
        )
        for row in latency_summary.itertuples()
    ][:12]
    return (
        "\\section{Results}\n"
        f"Measured results were read from \\texttt{{results/metrics.csv}}. "
        f"The lowest mean MAE in the generated run was obtained by \\texttt{{{method}}} "
        f"with MAE {mae:.4f}. These values are generated from local experiment traces, "
        f"not projected or fabricated estimates.{fallback_note}{source_note}\n\n"
        "\\paragraph{Robustness ranking.}\n"
        + "\\\\\n".join(method_lines)
        + "\n\n\\paragraph{Agentic safety variants.}\n"
        + ("\\\\\n".join(safety_lines) if safety_lines else "No agentic safety variants were recorded.")
        + "\n\n\\paragraph{Latency summary.}\n"
        + "\\\\\n".join(latency_lines)
        + "\n"
    )


def main() -> None:
    ensure_dir("paper/sections")
    ensure_dir("paper/appendices")
    write_tex("paper/sections/04_experimental_setup.tex", METHODOLOGY_TEMPLATE.strip() + "\n")
    write_tex("paper/sections/05_results.tex", results_section())
    write_tex("paper/sections/06_discussion.tex", DISCUSSION_TEMPLATE.strip() + "\n")
    write_tex(
        "paper/appendices/appendix_reproducibility.tex",
        "\\section{Reproducibility}\nRun \\texttt{make discover-data audit-data test run-small paper}.\n",
    )
    write_tex(
        "paper/appendices/appendix_code_snippets.tex",
        "\\section{Code Snippets}\nCore APIs are implemented under \\texttt{src/}.\n",
    )
    report_md = Path("paper/report.md")
    report_md.write_text(
        "# Agentic Lightweight Consensus Report\n\n"
        "Generated sections are available under `paper/sections/`. "
        "Results are populated only from measured CSV files in `results/`.\n",
        encoding="utf-8",
    )


if __name__ == "__main__":
    main()
